### ISSUE TITLE
Replace build.sh with build.dart

### ISSUE THREAD

**Issue by oddrationale** [oddrationale/dart_libsass#1]
Re-write the build script using Dart instead of Bash.

**Comment by oddrationale** [comment]
Consider using https://github.com/mezoni/build_tools with https://github.com/mezoni/ccompilers or https://github.com/mezoni/ccompile

**Comment by oddrationale** [comment]
Need to also seriously consider CMake as a build system.

**Comment by m0gg** [comment]
Wrote https://gist.github.com/m0gg/66a0f7a92b1435757124
It works but the code is not very satisfying...
My opinion: you should wait for a pub mechanism for native extensions.

**Comment by oddrationale** [comment]
@m0gg Thanks for the contribution! I've committed it to the repo. I don't have a Mac. Have you tested it on Mac?

**Comment by oddrationale** [comment]
Note to self: Update README and remove old build.sh script.

**Comment by m0gg** [comment]
Some kind of, its not a mac, just a notebook that runs them all :) 
Compilation is successcull on osx, but the outfile is significant smaller than on linux. I have not testet the lib itself.
